# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "The Slotkin Laboratory"  # the name of your site, e.g. ACME Corp.
name                     : &name "Keith Slotkin" # &name is a YAML anchor which can be *referenced later
description              : &description "Slotkin lab at Donald Danforth Plant Science Center"
url                      : "https://slotkinlab/github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
search                   : false # true, false (default)
search_full_content      : false # true, false (default)
# Social Sharing
twitter:
  username               : &twitter "Slotkin_Lab"
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Slotkin_Lab"

defaults:
  # _posts
  - scope:
      path: ""
    values:
      author_profile: false

# Reading Files
include:
  - .htaccess
  - _pages
  - people
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .DS_Store
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-twitter-plugin


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-twitter-plugin
# Collections
collections:
  people:
    output: true
    permalink: /:collection/:path/
